DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS criminal;

CREATE TABLE user(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL ,
  password TEXT NOT NULL,
  is_manager BOOLEAN NOT NULL
);

CREATE TABLE criminal(
  rank INTEGER PRIMARY KEY AUTOINCREMENT,
  id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  encoding TEXT NOT NULL ,
  important BOOLEAN DEFAULT FALSE
);